Emigration complete
Issue
Assets/Script/AI/AICard.cs(25,41): error CS1644: Feature `interpolated strings' cannot be used because it is not part of the C# 4.0 language specification